### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by alanshaw**
Caused a big spike in bundle size compared to 0.34.1!

https://bundlephobia.com/result?p=ipfs@0.34.2

### CODE REVIEW

**Comment by alanshaw** [comment]
@mkg20001 looks like ipv6 is not enabled/working on travis - the tests pass locally.

Maybe it needs to switch to an env that supports ipv6? https://github.com/njh/travis-ipv6-test

**Comment by alanshaw** [comment]
ping @mkg20001 can we get this merged and released?

**Comment by mkg20001** [comment]
@alanshaw Sorry for not getting to this. Life got in the way ;)

The IPv6 tests are always buggy on travis, I think they should be skipped or we can switch CI to jenkins after a move to libp2p (ref #2)

**Comment by mkg20001** [comment]
So after finally conquering the school-proxies and commiting the fix thanks to a script...

script

...here is the merge :tada:

**Comment by mkg20001** [comment]
Btw, I messed up releases a bit. Need to do git via tor but npm via HTTP (otherwise things are slow as hell). Now doing git+npm via tor, seems to work but is hellish slow. Hate this setup, but at least the teachers are fine with me doing whatever I want during IT.

**Pull request merged**
